### ISSUE TITLE
Tables in documentation content not working

### ISSUE THREAD

**Issue by simondean** [adrobisch/raml-converter#15]
Hi.  Tables don't seem to work in documentation content.  I can get things like lists and headers working but not tables.  

Here's an example:

``` yaml
#%RAML 0.8
title: Example
documentation:
  - title: Example
    content: |
      Here is a list:

      * One
      * Two

      Here is a table:

      | One | Two |
      | --- | --- |
      | A   | B   |
```

Here's the resulting HTML from raml-convert:

``` html
<body data-spy="scroll" data-target="#sidebar">
    <div class="container">
        <div class="row">
            <div class="col-md-9" role="main">
                <div class="page-header">
                    <h1>Example documentation</h1>
                    <p><a href=""></a></p>


                        <h3 id=""><a href="#">Example</a></h3>
                        <p>Here is a list:</p>
<ul>
  <li>One</li>
  <li>Two</li>
</ul><p>Here is a table:</p><p>| One | Two | | --- | --- | | A | B |</p>

                </div>
                <h2>Resources</h2>


            </div>

            <div class="col-md-3">
                <div id="sidebar" class="hidden-print affix" role="complementary">
                    <ul class="nav nav-pills nav-stacked">

                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
```

You can see the tables aren't being converted to HTML.  

Thanks
